name: build

on:
  pull_request:
  push:
    branches:
      - master
      - feature/githubaction

jobs: 
  build:
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install
      run: npm i

    - name: build
      run: npm run build

    - name: Release
      run: npm run semantic-release && npm run coveralls
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
